spring.application.name=spring1

spring.datasource.url=jdbc:mysql://localhost:3306/microf_invest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

server.address=0.0.0.0
server.port=8083

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# FORCE InnoDB (OBLIGATOIRE POUR LES FK)
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

server.servlet.context-path=/mfi