package tn.esprit.spring1.Services;

import com.google.zxing.qrcode.QRCodeWriter;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import org.knowm.xchart.*;
import org.springframework.stereotype.Service;
import tn.esprit.spring1.entities.Investment;
import tn.esprit.spring1.entities.Project;

import com.google.zxing.*;
import com.google.zxing.common.BitMatrix;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.util.*;
import java.util.List;

@Service
public class InvestorPdfService {

    public byte[] generateInvestorReport(Project project,
                                         List<Investment> investments,
                                         double success,
                                         String explanation,
                                         String baseUrl) throws Exception {

        Document document = new Document(PageSize.A4, 40, 40, 40, 40);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);
        document.open();

        java.awt.Color bg = new java.awt.Color(248,250,252);
        java.awt.Color text = new java.awt.Color(30,41,59);

        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, text);
        Font sectionFont = new Font(Font.HELVETICA, 13, Font.BOLD, text);
        Font normal = new Font(Font.HELVETICA, 11, Font.NORMAL, text);

        Paragraph title = new Paragraph("🚀 MicroFunding AI", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(5);

        Paragraph sub = new Paragraph("Smart Investment Dashboard", normal);
        sub.setAlignment(Element.ALIGN_CENTER);
        sub.setSpacingAfter(20);

        document.add(title);
        document.add(sub);

        // PROJECT
        document.add(createCard("📌 Project Overview", Arrays.asList(
                "Name: " + project.getName(),
                "Funding Goal: " + project.getFundingGoal() + " TND",
                "Collected: " + project.getCollectedAmount() + " TND"
        )));

        document.add(new Paragraph(" "));

        // AI
        document.add(createCard("🧠 AI Analysis", Arrays.asList(
                "Success Probability: " + (int)(success * 100) + "%",
                success > 0.7 ? "✔ Strong opportunity" : "⚠ Medium risk",
                "Insight:",
                explanation
        )));

        document.add(new Paragraph(" "));

        if (investments == null) investments = new ArrayList<>();

        // CHART
        Image chart = generateChart(investments);
        chart.scaleToFit(500, 280);
        chart.setAlignment(Image.ALIGN_CENTER);
        document.add(chart);

        document.add(new Paragraph(" "));

        // TABLE (🔥 PRO)
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3,3,2});

        table.addCell(createHeaderCell("Investor"));
        table.addCell(createHeaderCell("Amount"));
        table.addCell(createHeaderCell("Equity"));

        for (Investment i : investments) {
            table.addCell(createCell(i.getInvestor().getName()));
            table.addCell(createCell(String.format("%.2f TND", i.getAmount())));
            table.addCell(createCell(String.format("%.1f %%", i.getEquityShare())));
        }

        document.add(table);

        document.add(new Paragraph(" "));

        // WHY
        document.add(createCard("🤖 Why these investors?", Arrays.asList(
                "✔ Selected based on capital strength",
                "✔ Good match with project profile",
                "✔ Optimized risk distribution"
        )));

        document.add(new Paragraph(" "));

        // QR CENTERED
        String qrUrl = baseUrl + "/mfi/ai/dashboard/" + project.getIdProject();

        Image qr = generateQRCode(qrUrl);
        qr.scaleToFit(120,120);
        qr.setAlignment(Image.ALIGN_CENTER);

        Paragraph qrText = new Paragraph("📱 Scan to view full AI Dashboard",
                new Font(Font.HELVETICA, 12, Font.BOLD, text));
        qrText.setAlignment(Element.ALIGN_CENTER);

        document.add(qrText);
        document.add(new Paragraph(" "));
        document.add(qr);

        document.add(new Paragraph("\nGenerated by MicroFunding AI",
                new Font(Font.HELVETICA, 9, Font.ITALIC)));

        document.close();
        return out.toByteArray();
    }

    // CARD
    private PdfPTable createCard(String titleText, List<String> lines) {

        java.awt.Color bg = new java.awt.Color(248,250,252);

        PdfPTable card = new PdfPTable(1);
        card.setWidthPercentage(100);

        PdfPCell cell = new PdfPCell();
        cell.setPadding(18);
        cell.setBackgroundColor(bg);
        cell.setBorder(Rectangle.NO_BORDER);

        cell.addElement(new Paragraph(titleText, new Font(Font.HELVETICA,13,Font.BOLD)));

        for (String l : lines) {
            cell.addElement(new Paragraph(l));
        }

        card.addCell(cell);
        return card;
    }

    // HEADER CELL
    private PdfPCell createHeaderCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text,
                new Font(Font.HELVETICA,11,Font.BOLD, java.awt.Color.WHITE)));

        cell.setBackgroundColor(new java.awt.Color(59,130,246));
        cell.setPadding(8);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBorderColor(java.awt.Color.WHITE);

        return cell;
    }

    // NORMAL CELL
    private PdfPCell createCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(8);
        cell.setBorderColor(new java.awt.Color(220,220,220));
        return cell;
    }

    // CHART
    private Image generateChart(List<Investment> investments) throws Exception {

        PieChart chart = new PieChartBuilder()
                .width(500)
                .height(300)
                .title("Distribution")
                .build();

        chart.getStyler().setLegendPosition(org.knowm.xchart.style.Styler.LegendPosition.OutsideS);
        chart.getStyler().setLegendLayout(org.knowm.xchart.style.Styler.LegendLayout.Horizontal);
        chart.getStyler().setLabelsVisible(true);

        java.awt.Color[] colors = new java.awt.Color[] {
                new java.awt.Color(59,130,246),
                new java.awt.Color(249,115,22)
        };
        chart.getStyler().setSeriesColors(colors);

        double total = investments.stream().mapToDouble(Investment::getAmount).sum();

        for (Investment i : investments) {
            double percent = (i.getAmount() / total) * 100;

            chart.addSeries(
                    i.getInvestor().getName() + " (" + String.format("%.1f", percent) + "%)",
                    i.getAmount()
            );
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        BitmapEncoder.saveBitmap(chart, baos, BitmapEncoder.BitmapFormat.PNG);

        return Image.getInstance(baos.toByteArray());
    }

    // QR
    private Image generateQRCode(String url) throws Exception {

        QRCodeWriter writer = new QRCodeWriter();
        BitMatrix matrix = writer.encode(url, BarcodeFormat.QR_CODE, 150, 150);

        BufferedImage image = new BufferedImage(150,150,BufferedImage.TYPE_INT_RGB);

        for(int x=0;x<150;x++){
            for(int y=0;y<150;y++){
                image.setRGB(x,y, matrix.get(x,y) ? 0x000000 : 0xFFFFFF);
            }
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ImageIO.write(image,"png",baos);

        return Image.getInstance(baos.toByteArray());
    }
}